replicaCount: 1

image:
    repository: yenhung/node-deploy-demo
    tag: latest
    pullPolicy: Always

service:
    type: LoadBalancer
    port: 3000

app:
    name: node-deploy-demo-dev

env:
  APP_VERSION: dev

# Redis 配置
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0 