replicaCount: 1

image:
    repository: yenhung/node-deploy-demo
    tag: latest
    pullPolicy: IfNotPresent

service:
    type: NodePort
    port: 3000
    nodePort: 31000

app:
    name: node-deploy-demo

env:
  APP_VERSION: v2
