apiVersion: apps/v1
kind: Deployment
metadata:
    name: node-deploy-demo
    labels:
        app: node-deploy-demo
spec:
    replicas: 1
    selector:
        matchLabels:
            app: node-deploy-demo
    template:
        metadata:
            labels:
                app: node-deploy-demo
        spec:
            containers:
                - name: node-deploy-demo
                  image: yenhung/node-deploy-demo:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
                  resources:
                      limits:
                          cpu: "0.5"
                          memory: "256Mi"
                      requests:
                          cpu: "0.2"
                          memory: "128Mi"
                  env:
                      - name: NODE_ENV
                        value: "production"
                      - name: WEBHOOK_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: node-deploy-demo-secrets
                                key: webhook-secret
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 3000
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 3000
                      initialDelaySeconds: 5
                      periodSeconds: 5
---
apiVersion: v1
kind: Secret
metadata:
    name: node-deploy-demo-secrets
type: Opaque
stringData:
    webhook-secret: "change-this-in-production"
