apiVersion: v1
kind: Service
metadata:
    name: node-deploy-demo-service
    labels:
        app: node-deploy-demo
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 3000
          nodePort: 30080
          protocol: TCP
    selector:
        app: node-deploy-demo
