name: Helm Deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: yenhung/node-deploy-demo:latest,yenhung/node-deploy-demo:${{ github.sha }}

            - name: Set up kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: "v1.27.1"

            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                  version: "v3.14.0"

            - name: Decode kubeconfig
              run: |
                  echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > kubeconfig
                  export KUBECONFIG=$PWD/kubeconfig

            - name: Helm Upgrade
              run: |
                  helm upgrade --install node-deploy-demo ./node-deploy-demo-chart \
                    --set image.tag=${{ github.sha }} \
                    --set env.APP_VERSION=${{ github.sha }}
